version: '3'

services:
  server:
    build: './nginx'

    volumes:
      - ~/budget-app/build/React:/usr/share/nginx/html
      - ~/budget-app/nginx/:/etc/nginx/conf.d

    ports:
      - "80:80"

    networks:
      - default

    restart:
      - always

  db:
    image: mysql:latest

    expose:
      - 3306

    ports:
      - 3306:3306

    networks:
     - spring-network

    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=moolah

  spring:
    build: './Java'

    depends_on:
      - db

    expose:
      - 8080

    ports:
      - 8080:8080

    networks:
     - spring-network

    restart:
      - always

networks:
    spring-network:
        driver: bridge
